name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Jest explicitly
        run: npm install --save-dev jest

      - name: Ensure Jest is executable
        run: chmod +x node_modules/.bin/jest

      - name: Verify Jest installation
        run: npx jest --version

      - name: Run tests
        run: npx jest

      - name: Archive production artifacts
        run: zip -r app.zip . -x "node_modules/*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: |
          ls -la
          cat Dockerfile

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/midterm-assignment:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/midterm-assignment:latest